"""new fields in user model

Revision ID: 4179dacd7b4e
Revises: d5928ae37471
Create Date: 2022-07-17 21:28:56.848907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4179dacd7b4e'
down_revision = 'd5928ae37471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset__update', sa.Column('asset', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset__update', 'asset')
    # ### end Alembic commands ###
